using NUnit.Framework;

namespace Catpic.Social.Tests
{
    [TestFixture]
    public class ActivityStreamsExpressionTests
    {
        [TestCase(
       "[{\"method\":\"activitystreams.get\",\"id\":\"activitystreams.get\",\"params\":{\"userId\":\"john.doe\",\"groupId\":\"@self\"}}]",
       "[{\"result\":{\"startIndex\":0,\"itemsPerPage\":25,\"totalResults\":3,\"filtered\":false,\"sorted\":false,\"updatedSince\":true,\"list\":[{\"userId\":\"john.doe\",\"id\":\"activity1\",\"title\":\"John shared new photos with you\",\"published\":\"2011-02-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object1\",\"url\":\"http://example.org/blog/2011/02/entry\"},\"target\":{\"id\":\"target1\",\"displayName\":\"John's Blog\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}},{\"userId\":\"john.doe\",\"id\":\"activity2\",\"title\":\"John posted a new photo album.\",\"published\":\"2011-03-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object2\",\"url\":\"http://example.org/album/my_fluffy_cat.jpg\"},\"target\":{\"id\":\"target2\",\"displayName\":\"John's Photo Album\",\"url\":\"http://example.org/album/\",\"objectType\":\"photo-album\"}},{\"userId\":\"john.doe\",\"id\":\"activity3\",\"title\":\"John posted a new photo to his blog\",\"published\":\"2012-06-02T10:02:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object3\",\"url\":\"http://example.org/album/new_world.jpg\"},\"target\":{\"id\":\"target3\",\"displayName\":\"John's Blog About Life\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}}]},\"id\":\"activitystreams.get\"}]")]
        public void CanLoadSelf(string query, string expectedResult)
        {
            TestHelper.AsertResult(query, expectedResult);
        }

        [TestCase(
        "[{\"method\":\"activitystreams.get\",\"id\":\"activitystreams.get\",\"params\":{\"userId\":\"john.doe\",\"groupId\":\"@self\",\"filterBy\":\"id\",\"filterValue\":\"activity1\",\"filterOp\": \"equals\",\"sortBy\":\"userId\",\"sortOrder\":\"ascending\",}}]",
        "[{\"result\":{\"startIndex\":0,\"itemsPerPage\":25,\"totalResults\":1,\"filtered\":true,\"sorted\":true,\"updatedSince\":true,\"list\":[{\"userId\":\"john.doe\",\"id\":\"activity1\",\"title\":\"John shared new photos with you\",\"published\":\"2011-02-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object1\",\"url\":\"http://example.org/blog/2011/02/entry\"},\"target\":{\"id\":\"target1\",\"displayName\":\"John's Blog\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}}]},\"id\":\"activitystreams.get\"}]")]
        public void CanFilterSelf(string query, string expectedResult)
        {
            TestHelper.AsertResult(query, expectedResult);
        }

        [TestCase(
       "[{\"method\":\"activitystreams.create\",\"id\":\"activitystreams.create\",\"params\":{\"userId\":\"@viewer\",\"groupId\":\"@self\",\"activity\":{\"published\":\"2010-04-27T06:02:36\",\"title\":\"ads\",\"content\":\"asd\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\"},\"verb\":\"play\",\"object\":{\"id\":1343334061978,\"displayName\":\"asd\",\"url\":\"asd\",\"objectType\":\"folder\",\"summary\":\"asd\"}}}}]",
       "[{\"result\":{\"userId\":\"john.doe\",\"id\":\"4\",\"title\":\"ads\",\"published\":\"2010-04-27T06:02:36\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\"},\"verb\":\"play\",\"object\":{\"id\":\"1343334061978\",\"displayName\":\"asd\",\"url\":\"asd\",\"objectType\":\"folder\"}},\"id\":\"activitystreams.create\"}]",
       "[{\"method\":\"activitystreams.get\",\"id\":\"activitystreams.get\",\"params\":{\"userId\":\"john.doe\",\"groupId\":\"@self\"}}]",
       "[{\"result\":{\"startIndex\":0,\"itemsPerPage\":25,\"totalResults\":4,\"filtered\":false,\"sorted\":false,\"updatedSince\":true,\"list\":[{\"userId\":\"john.doe\",\"id\":\"activity1\",\"title\":\"John shared new photos with you\",\"published\":\"2011-02-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object1\",\"url\":\"http://example.org/blog/2011/02/entry\"},\"target\":{\"id\":\"target1\",\"displayName\":\"John's Blog\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}},{\"userId\":\"john.doe\",\"id\":\"activity2\",\"title\":\"John posted a new photo album.\",\"published\":\"2011-03-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object2\",\"url\":\"http://example.org/album/my_fluffy_cat.jpg\"},\"target\":{\"id\":\"target2\",\"displayName\":\"John's Photo Album\",\"url\":\"http://example.org/album/\",\"objectType\":\"photo-album\"}},{\"userId\":\"john.doe\",\"id\":\"activity3\",\"title\":\"John posted a new photo to his blog\",\"published\":\"2012-06-02T10:02:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object3\",\"url\":\"http://example.org/album/new_world.jpg\"},\"target\":{\"id\":\"target3\",\"displayName\":\"John's Blog About Life\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}},{\"userId\":\"john.doe\",\"id\":\"4\",\"title\":\"ads\",\"published\":\"2010-04-27T06:02:36\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\"},\"verb\":\"play\",\"object\":{\"id\":\"1343334061978\",\"displayName\":\"asd\",\"url\":\"asd\",\"objectType\":\"folder\"}}]},\"id\":\"activitystreams.get\"}]")]
        public void CanCreate(string query1, string expectedResult1, string query2, string expectedResult2)
        {
            TestHelper.DoubleCheck(query1, expectedResult1, query2, expectedResult2);
        }

        [TestCase(
      "[{\"method\":\"activitystreams.update\",\"id\":\"activitystreams.update\",\"params\":{\"userId\":\"@viewer\",\"groupId\":\"@self\",\"activity\":{\"id\":\"activity1\",\"title\":\"new title\"}}}]",
      "[{\"result\":{\"userId\":\"john.doe\",\"id\":\"activity1\",\"title\":\"new title\",\"published\":\"2011-02-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object1\",\"url\":\"http://example.org/blog/2011/02/entry\"},\"target\":{\"id\":\"target1\",\"displayName\":\"John's Blog\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}},\"id\":\"activitystreams.update\"}]",
      "[{\"method\":\"activitystreams.get\",\"id\":\"activitystreams.get\",\"params\":{\"userId\":\"john.doe\",\"groupId\":\"@self\"}}]",
      "[{\"result\":{\"startIndex\":0,\"itemsPerPage\":25,\"totalResults\":3,\"filtered\":false,\"sorted\":false,\"updatedSince\":true,\"list\":[{\"userId\":\"john.doe\",\"id\":\"activity1\",\"title\":\"new title\",\"published\":\"2011-02-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object1\",\"url\":\"http://example.org/blog/2011/02/entry\"},\"target\":{\"id\":\"target1\",\"displayName\":\"John's Blog\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}},{\"userId\":\"john.doe\",\"id\":\"activity2\",\"title\":\"John posted a new photo album.\",\"published\":\"2011-03-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object2\",\"url\":\"http://example.org/album/my_fluffy_cat.jpg\"},\"target\":{\"id\":\"target2\",\"displayName\":\"John's Photo Album\",\"url\":\"http://example.org/album/\",\"objectType\":\"photo-album\"}},{\"userId\":\"john.doe\",\"id\":\"activity3\",\"title\":\"John posted a new photo to his blog\",\"published\":\"2012-06-02T10:02:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object3\",\"url\":\"http://example.org/album/new_world.jpg\"},\"target\":{\"id\":\"target3\",\"displayName\":\"John's Blog About Life\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}}]},\"id\":\"activitystreams.get\"}]")]
        public void CanUpdate(string query1, string expectedResult1, string query2, string expectedResult2)
        {
            TestHelper.DoubleCheck(query1, expectedResult1, query2, expectedResult2);
        }

        [TestCase(
        "[{\"method\":\"activitystreams.delete\",\"id\":\"activitystreams.delete\",\"params\":{\"userId\":\"@viewer\",\"groupId\":\"@self\",\"activityId\":\"activity1\"}}]",
        "[{\"result\":{},\"id\":\"activitystreams.delete\"}]",
        "[{\"method\":\"activitystreams.get\",\"id\":\"activitystreams.get\",\"params\":{\"userId\":\"john.doe\",\"groupId\":\"@self\"}}]",
        "[{\"result\":{\"startIndex\":0,\"itemsPerPage\":25,\"totalResults\":2,\"filtered\":false,\"sorted\":false,\"updatedSince\":true,\"list\":[{\"userId\":\"john.doe\",\"id\":\"activity2\",\"title\":\"John posted a new photo album.\",\"published\":\"2011-03-10T15:04:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object2\",\"url\":\"http://example.org/album/my_fluffy_cat.jpg\"},\"target\":{\"id\":\"target2\",\"displayName\":\"John's Photo Album\",\"url\":\"http://example.org/album/\",\"objectType\":\"photo-album\"}},{\"userId\":\"john.doe\",\"id\":\"activity3\",\"title\":\"John posted a new photo to his blog\",\"published\":\"2012-06-02T10:02:55Z\",\"actor\":{\"id\":\"john.doe\",\"displayName\":\"John Doe\",\"url\":\"http://example.org/john\",\"objectType\":\"person\",\"image\":{\"url\":\"http://example.org/john/image\",\"width\":250,\"height\":250,\"duration\":0,\"mediaItemId\":0}},\"verb\":\"post\",\"object\":{\"id\":\"object3\",\"url\":\"http://example.org/album/new_world.jpg\"},\"target\":{\"id\":\"target3\",\"displayName\":\"John's Blog About Life\",\"url\":\"http://example.org/blog/\",\"objectType\":\"blog\"}}]},\"id\":\"activitystreams.get\"}]")]
        public void CanDelete(string query1, string expectedResult1, string query2, string expectedResult2)
        {
            TestHelper.DoubleCheck(query1, expectedResult1, query2, expectedResult2);
        }
    }
}
